# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unit-test:
    docker:
      - image: googleapis/nox:0.18.2

    steps:
      - checkout
      - run:
          command: |
            nox -f django_cloud_deploy/nox.py -s unit_test
  lint:
    docker:
      - image: googleapis/nox:0.18.2

    steps:
      - checkout
      - run:
          command: |
            nox -f django_cloud_deploy/nox.py -s lint
  integration-test:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - run:
          name: Install Nox
          command: |
            apt-get -qqy install python3-pip
            python3 -m pip install --upgrade nox-automation
      - run:
          name: Install Cloud SQL Proxy
          command: |
            curl -L -o /usr/local/bin/cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
            chmod +x /usr/local/bin/cloud_sql_proxy
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.0"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv -f /tmp/docker/* /usr/bin
      - run:
          name: Dump Google Cloud Credentials to file
          command: |
            echo ${GCP_CREDENTIAL} > credentials.json
            gcloud auth activate-service-account --key-file credentials.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Run Test
          command: |
            nox -f django_cloud_deploy/nox.py -s integration_test  

workflows:
  version: 2
  unit_test:
    jobs:
      - unit-test
  lint:
    jobs:
      - lint
  integration_test:
    jobs:
      - integration-test
