# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unit-test:
    docker:
      - image: googleapis/nox:0.18.2

    steps:
      - checkout
      - run:
          command: |
            nox -f django_cloud_deploy/nox.py -s unit_test
  lint:
    docker:
      - image: googleapis/nox:0.18.2

    steps:
      - checkout
      - run:
          command: |
            nox -f django_cloud_deploy/nox.py -s lint
  integration-test:
    docker:
      - image: circleci/python

    steps:
      - checkout
      - run:
          command: |
            sudo python3 -m pip install --upgrade nox-automation
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-230.0.0-linux-x86_64.tar.gz -O ~/google-cloud-sdk.tar.gz
            tar -xzf ~/google-cloud-sdk.tar.gz -C ~/
            source ~/google-cloud-sdk/install.sh
            if [ -n "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
              sudo openssl aes-256-cbc -d -a -k "$GOOGLE_CREDENTIALS_PASSPHRASE" \
                  -in credentials.json.enc \
                  -out $GOOGLE_APPLICATION_CREDENTIALS
            else
              echo "No credentials. Integration tests will not run."
            fi
            nox -f django_cloud_deploy/nox.py -s integration_test  

workflows:
  version: 2
  unit_test:
    jobs:
      - unit-test
  lint:
    jobs:
      - lint
  integration_test:
    jobs:
      - integration-test
